"""TTS (Text-to-Speech) routes – powered by the ElevenLabs API."""

import hashlib
import logging

import fastapi
from fastapi.responses import Response
from pydantic import BaseModel, Field

from src.api.dependencies.auth import get_current_user
from src.api.dependencies.rate_limit import rate_limiter
from src.config.manager import settings
from src.repository.redis_client import async_redis
from src.services.elevenlabs_tts import generate_tts_audio

router = fastapi.APIRouter(prefix="/tts", tags=["tts"])
logger = logging.getLogger(__name__)


def _tts_cache_key(text: str, voice_id: str | None) -> str:
    digest = hashlib.sha256(f"{voice_id or settings.ELEVENLABS_VOICE_ID}:{text}".encode()).hexdigest()
    return f"tts_cache:{digest}"


async def _get_cached_audio(cache_key: str) -> bytes | None:
    """Interview questions repeat heavily across users, so caching by
    (text, voice_id) cuts both ElevenLabs cost and latency on hits. Best
    effort - any Redis error is treated as a cache miss, never an error."""
    try:
        return await async_redis.client.get(cache_key)
    except Exception as exc:
        logger.warning("TTS cache read failed, treating as miss: %s", exc)
        return None


async def _set_cached_audio(cache_key: str, audio_bytes: bytes) -> None:
    try:
        await async_redis.client.set(cache_key, audio_bytes, ex=settings.TTS_CACHE_TTL_SECONDS)
    except Exception as exc:
        logger.warning("TTS cache write failed (non-fatal): %s", exc)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------


class TTSRequest(BaseModel):
    text: str = Field(
        ...,
        min_length=1,
        max_length=5_000,
        description="Text to convert to speech (max 5 000 characters).",
        examples=["Hello, welcome to Samvaad Sathi!"],
    )
    voice_id: str | None = Field(
        default=None,
        description=(
            "Optional ElevenLabs voice ID. "
            "Defaults to the ELEVENLABS_VOICE_ID setting when omitted."
        ),
        examples=["JBFqnCBsd6RMkjVDRTpX"],
    )


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post(
    path="/convert",
    name="tts:convert",
    status_code=fastapi.status.HTTP_200_OK,
    summary="Convert text to speech via ElevenLabs",
    description=(
        "Accepts a text payload and returns an MP3 audio file generated by the "
        "ElevenLabs text-to-speech API. "
        "Requires a valid Bearer token. "
        "Max input length is 5 000 characters."
    ),
    response_class=Response,
    responses={
        200: {
            "content": {"audio/mpeg": {}},
            "description": "MP3 audio file of the synthesised speech.",
        },
        400: {"description": "Bad request – e.g. empty text."},
        503: {"description": "ElevenLabs service unavailable or not configured."},
    },
)
async def convert_text_to_speech(
    payload: TTSRequest,
    current_user=fastapi.Depends(get_current_user),
    _rate_limit=fastapi.Depends(
        rate_limiter(key_prefix="tts", limit=settings.RATE_LIMIT_TTS_PER_MINUTE, window_seconds=60)
    ),
) -> Response:
    """
    Converts ``payload.text`` to speech using ElevenLabs and streams back an
    MP3 file directly. Serves from a Redis cache when the same (text, voice_id)
    pair has been synthesised before.
    """
    cache_key = _tts_cache_key(payload.text, payload.voice_id)
    cached_audio = await _get_cached_audio(cache_key)
    if cached_audio:
        logger.info(
            "TTS cache hit | User=%s | Chars=%d",
            getattr(current_user, "id", None),
            len(payload.text),
        )
        return Response(
            content=cached_audio,
            media_type="audio/mpeg",
            headers={
                "X-TTS-Status": "cached",
                "Content-Disposition": 'attachment; filename="tts_output.mp3"',
            },
        )

    try:
        audio_bytes, error, latency_ms = await generate_tts_audio(
           text=payload.text,
           voice_id=payload.voice_id,
        )

        if error:
        # status = (
        #     fastapi.status.HTTP_503_SERVICE_UNAVAILABLE
        #     if "not configured" in error or "not installed" in error
        #     else fastapi.status.HTTP_502_BAD_GATEWAY
        # )
        # raise fastapi.HTTPException(status_code=status, detail=error)
            logger.warning(
            "TTS convert failed (fallback triggered) | User=%s | Error=%s",
            getattr(current_user, "id", None),
            error,
            )
            return Response(
                content=b"",
                media_type="audio/mpeg",
                headers={
                    "X-Latency-Ms": str(latency_ms or 0),
                    "X-TTS-Status": "fallback_failed",
                    "X-TTS-Error": str(error)[:200],
                },
            )
        logger.info(
            "TTS convert success | User=%s | Chars=%d | Latency=%dms",
            getattr(current_user, "id", None),
            len(payload.text),
            latency_ms or 0,
        )

        await _set_cached_audio(cache_key, audio_bytes)

        return Response(
            content=audio_bytes,
            media_type="audio/mpeg",
            headers={
                "X-Latency-Ms": str(latency_ms or 0),
                "X-TTS-Status": "success",
                "Content-Disposition": 'attachment; filename="tts_output.mp3"',
            },
        )

    except Exception as exc:

        logger.exception(
            "Unexpected error in TTS conversion | User=%s | Error=%s",
            getattr(current_user, "id", None),
            str(exc),
        )
        #UNHANDLED EXCEPTION CATCH: Never crash the API with 500/502
        return Response(
            content=b"",
            media_type="audio/mpeg",
            headers={
                "X-TTS-Status": "fallback_exception",
                "X-TTS-Error": str(exc)[:200],
            },
        )
