"""Added user profiling attributes to user's table

Revision ID: 5cb484ca39a5
Revises: 0db6df8cca11
Create Date: 2025-09-14 11:35:44.596667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb484ca39a5'
down_revision = '0db6df8cca11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The preceding migration creates a non-unique index with this name; it
    # does not create a unique constraint. Dropping a constraint here makes a
    # clean database fail midway through `alembic upgrade head`.
    op.drop_index(op.f('ix_report_interview_id'), table_name='report')
    op.create_index(op.f('ix_report_interview_id'), 'report', ['interview_id'], unique=True)
    op.add_column('user', sa.Column('degree', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('university', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('profile_picture', sa.LargeBinary(), nullable=True))
    # The current model stores the display value (for example,
    # "Frontend Development") as a string. Using a PostgreSQL enum here both
    # disagreed with the model and failed on clean databases because the enum
    # type had never been created.
    op.add_column('user', sa.Column('target_position', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('company', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company')
    op.drop_column('user', 'target_position')
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'university')
    op.drop_column('user', 'degree')
    op.drop_index(op.f('ix_report_interview_id'), table_name='report')
    op.create_index(op.f('ix_report_interview_id'), 'report', ['interview_id'], unique=False)
    # ### end Alembic commands ###
