"""Add remaining missing tables

Revision ID: f04f4122dd5b
Revises: b7eb7787beee
Create Date: 2026-09-08 11:35:21.839694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f04f4122dd5b'
down_revision = 'b7eb7787beee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('track', sa.String(length=64), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_practice_interview_id'), 'structure_practice', ['interview_id'], unique=False)
    op.create_index(op.f('ix_structure_practice_status'), 'structure_practice', ['status'], unique=False)
    op.create_index(op.f('ix_structure_practice_track'), 'structure_practice', ['track'], unique=False)
    op.create_index(op.f('ix_structure_practice_user_id'), 'structure_practice', ['user_id'], unique=False)
    op.create_table('structure_practice_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['structure_practice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_practice_answer_practice_id'), 'structure_practice_answer', ['practice_id'], unique=False)
    op.create_index(op.f('ix_structure_practice_answer_question_index'), 'structure_practice_answer', ['question_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structure_practice_answer_question_index'), table_name='structure_practice_answer')
    op.drop_index(op.f('ix_structure_practice_answer_practice_id'), table_name='structure_practice_answer')
    op.drop_table('structure_practice_answer')
    op.drop_index(op.f('ix_structure_practice_user_id'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_track'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_status'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_interview_id'), table_name='structure_practice')
    op.drop_table('structure_practice')
    # ### end Alembic commands ###
