"""Actually create pronunciation_practice table

Revision ID: b7eb7787beee
Revises: daef9f7d4ec2
Create Date: 2026-09-08 11:27:38.696639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7eb7787beee'
down_revision = 'daef9f7d4ec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: pronunciation_practice was originally created in October 2025 (pronunciation_practice_001),
    # but was accidentally dropped in migration 95d25f35a7f6 (May 2026).
    # We are re-creating it here because it is currently missing on staging.
    op.create_table('pronunciation_practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_practice_difficulty'), 'pronunciation_practice', ['difficulty'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_status'), 'pronunciation_practice', ['status'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_user_id'), 'pronunciation_practice', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_practice_user_id'), table_name='pronunciation_practice')
    op.drop_index(op.f('ix_pronunciation_practice_status'), table_name='pronunciation_practice')
    op.drop_index(op.f('ix_pronunciation_practice_difficulty'), table_name='pronunciation_practice')
    op.drop_table('pronunciation_practice')
    # ### end Alembic commands ###
